### PR TITLE
Fix latest event ID

### LINKED ISSUE #289: Wrong Event ID after loading an existing database
In `commit()`, `inc_height()` stores the new height in the DB and returns the previous height.

The problem is that we use the previous height to set the new ID, i.e., `EventId::from(height << HEIGHT_EVENTID_SHIFT);`

If we stop and restart a node, `load()` fetches the height from the DB and computes the new ID in the same manner. The height in the DB _is the new height, not the old one_.

The values of `self.latest_XX_id` will differ between a node that never stopped and a node that was restarted **on the first block after the restart**.

If there's a transaction in that block then Tendermint will crash complaining that the AppHash is not the same

Relates #288

### PR DESCRIPTION
**Pull request by fmorency**
Fixes #289 

Contains #290

### CODE REVIEW

File: src/many-kvstore/src/storage.rs [hunk 1]
```diff
@@ -87,7 +87,15 @@ impl KvStoreStorage {
             u64::from_be_bytes(bytes)
         });
 
-        let latest_event_id = EventId::from(height << HEIGHT_EVENTID_SHIFT);
+        // The call to `saturating_sub()` is required to fix
```
Comment (hansl) [inline src/many-kvstore/src/storage.rs:90]: Can we just do the proper fix for kvstore since we haven't started a production network yet? Just store the `latest_event_id` in the database on `commit()` and +1 it every event.

**Review by hansl — CHANGES_REQUESTED** [review]

File: src/many-kvstore/src/storage.rs (hunk 1 above)
Comment (fmorency) [reply src/many-kvstore/src/storage.rs:90]: Yes of course

**Review by hansl — APPROVED** [review]
Approved, but I'd like to merge this after my Memo PR is in (unless I can't merge today). I'd really like the Memo refactor going in today.
